/**
 * hardware-export.js — Embedded C++ code generator for Grid Sentinel.
 *
 * Generates platform-specific C++ code for deploying the autoencoder
 * model on STM32, Arduino, or ESP32 microcontrollers.
 *
 * Generated code includes:
 *   - Clarke Transform matrix calculation
 *   - 1D convolution step and ReLU activation
 *   - Model weights (quantized int8 or float32)
 *   - Inference loop suitable for real-time embedded systems
 */

import { getModelArchitecture } from "./autoencoder-sim.js";

// ── C++ Code Generation ───────────────────────────────────────────

export function generateCppCode(platform = "stm32") {
  const arch = getModelArchitecture();
  const weights = generateQuantizedWeights(arch);
  const header = generateHeader(platform);
  const clarkeFn = generateClarkeTransform();
  const convFn = generateConv1D();
  const reluFn = generateRelu();
  const inferenceFn = generateInferenceLoop(arch);
  const mainLoop = generateMainLoop(platform);

  return `${header}

/*
 * Autoencoder Architecture:
 *   Input: 3 channels (Va, Vb, Vc)
 *   Encoder: Conv1D(3→16, k=7) → ReLU → Conv1D(16→32, k=5) → ReLU → Conv1D(32→64, k=3) → ReLU
 *   Decoder: Conv1D(64→32, k=3) → ReLU → Conv1D(32→16, k=5) → ReLU → Conv1D(16→3, k=7)
 *   Parameters: ~${arch.parameters.toLocaleString()}
 *   Threshold: calibration-dependent (set THRESHOLD_MSE and THRESHOLD_THD)
 */

#include <math.h>
#include <string.h>

/* ── Configuration ─────────────────────────────────────────── */
#define SAMPLE_RATE     10000
#define WINDOW_SIZE     100
#define NUM_PHASES      3
#define THRESHOLD_MSE   0.002f
#define THRESHOLD_THD   0.05f
#define FFT_SIZE        128

${weights}

/* ── Clarke Transform ──────────────────────────────────────── */
${clarkeFn}

/* ── 1D Convolution ───────────────────────────────────────── */
${convFn}

/* ── ReLU Activation ──────────────────────────────────────── */
${reluFn}

/* ── Forward Pass ─────────────────────────────────────────── */
${inferenceFn}

/* ── Main Loop ────────────────────────────────────────────── */
${mainLoop}
`;
}

// ── Header ────────────────────────────────────────────────────────
function generateHeader(platform) {
  const headers = {
    stm32: `/*
 * Grid Sentinel — STM32 Embedded Inference
 * Generated by Grid Sentinel Hardware Export
 * Target: STM32F4/H7 series (ARM Cortex-M4/M7)
 *
 * Requirements:
 *   - CMSIS DSP library for optimized math
 *   - ADC input at ${10000} Hz sampling rate
 *   - UART/SPI output for alerts
 */

#include "stm32f4xx_hal.h"
#include "arm_math.h"

/* Hardware abstraction */
#define ADC_BUFFER_SIZE  ${100 * 3}
#define ALERT_PIN        GPIO_PIN_13
#define ALERT_PORT       GPIOC`,

    arduino: `/*
 * Grid Sentinel — Arduino Embedded Inference
 * Generated by Grid Sentinel Hardware Export
 * Target: Arduino Uno/Mega/Nano (AVR ATmega328P/2560)
 *
 * Requirements:
 *   - Analog input A0-A2 for three-phase voltage
 *   - Serial output at 115200 baud for alerts
 *   - Optional: LED on pin 13 for visual alert
 */

#include <Arduino.h>

#define ADC_PIN_A    A0
#define ADC_PIN_B    A1
#define ADC_PIN_C    A2
#define ALERT_LED    13
#define SERIAL_BAUD  115200`,

    esp32: `/*
 * Grid Sentinel — ESP32 Embedded Inference
 * Generated by Grid Sentinel Hardware Export
 * Target: ESP32/ESP32-S3 (Xtensa LX6/LX7 or RISC-V)
 *
 * Requirements:
 *   - ADC input at ${10000} Hz sampling rate
 *   - WiFi/MQTT for remote alert delivery
 *   - Optional: OLED display for local status
 */

#include <Arduino.h>
#include <WiFi.h>
#include <PubSubClient.h>

#define ADC_PIN_A    36
#define ADC_PIN_B    39
#define ADC_PIN_C    34
#define ALERT_LED    2
#define SERIAL_BAUD  115200`,
  };

  return headers[platform] || headers.stm32;
}

// ── Quantized Weights ─────────────────────────────────────────────
function generateQuantizedWeights(arch) {
  // Generate placeholder weights structure
  // In production, these would be extracted from the trained PyTorch model
  const layers = [
    { name: "enc_conv0", inC: 3, outC: 16, k: 7 },
    { name: "enc_conv1", inC: 16, outC: 32, k: 5 },
    { name: "enc_conv2", inC: 32, outC: 64, k: 3 },
    { name: "dec_conv0", inC: 64, outC: 32, k: 3 },
    { name: "dec_conv1", inC: 32, outC: 16, k: 5 },
    { name: "dec_conv2", inC: 16, outC: 3, k: 7 },
  ];

  let weightsCode = "/* Model weights (quantized int8) */\n";
  weightsCode += "/* NOTE: Replace with actual trained weights */\n";
  weightsCode += "/* Export from Python: model.export_int8_weights() */\n\n";

  for (const layer of layers) {
    const size = layer.inC * layer.outC * layer.k;
    weightsCode += `static const int8_t ${layer.name}_weights[${size}] = {\n`;
    weightsCode += `  /* ${layer.inC}→${layer.outC}, k=${layer.k}, ${size} values */\n`;
    weightsCode += `  ${Array(Math.min(size, 16)).fill("0").join(", ")}${size > 16 ? ", /* ... */" : ""}\n`;
    weightsCode += `};\n\n`;

    weightsCode += `static const float ${layer.name}_bias[${layer.outC}] = {\n`;
    weightsCode += `  ${Array(Math.min(layer.outC, 8)).fill("0.0f").join(", ")}${layer.outC > 8 ? ", /* ... */" : ""}\n`;
    weightsCode += `};\n\n`;
  }

  weightsCode += `/* Quantization parameters */\n`;
  weightsCode += `#define WEIGHT_SCALE  0.0078125f  /* 1/128 */\n`;
  weightsCode += `#define WEIGHT_ZERO   0\n`;

  return weightsCode;
}

// ── Clarke Transform C++ ──────────────────────────────────────────
function generateClarkeTransform() {
  return `/**
 * Clarke Transform: abc → αβ0
 * Power-invariant form.
 *
 * @param va, vb, vc  Input three-phase voltages (p.u.)
 * @param alpha, beta, zero  Output Clarke components
 */
static inline void clarke_transform(float va, float vb, float vc,
                                     float *alpha, float *beta, float *zero) {
    const float SQRT3_OVER_2 = 0.8660254037844387f;
    *alpha = (2.0f / 3.0f) * (va - 0.5f * vb - 0.5f * vc);
    *beta  = (2.0f / 3.0f) * (SQRT3_OVER_2 * vb - SQRT3_OVER_2 * vc);
    *zero  = (1.0f / 3.0f) * (va + vb + vc);
}

/**
 * Batch Clarke Transform for window of samples.
 */
static void clarke_transform_batch(const float *va, const float *vb, const float *vc,
                                    float *alpha, float *beta, float *zero,
                                    int n) {
    const float SQRT3_OVER_2 = 0.8660254037844387f;
    for (int i = 0; i < n; i++) {
        alpha[i] = (2.0f / 3.0f) * (va[i] - 0.5f * vb[i] - 0.5f * vc[i]);
        beta[i]  = (2.0f / 3.0f) * (SQRT3_OVER_2 * vb[i] - SQRT3_OVER_2 * vc[i]);
        zero[i]  = (1.0f / 3.0f) * (va[i] + vb[i] + vc[i]);
    }
}`;
}

// ── 1D Convolution C++ ────────────────────────────────────────────
function generateConv1D() {
  return `/**
 * 1D Convolution step with valid padding.
 * Optimized for small kernels (k ≤ 7) on embedded targets.
 *
 * @param input    Input buffer [in_channels × input_length]
 * @param output   Output buffer [out_channels × output_length]
 * @param weights  Kernel weights [out_channels × in_channels × kernel_size]
 * @param bias     Bias terms [out_channels]
 * @param in_channels, out_channels, kernel_size, input_length
 */
static void conv1d_step(const float *input, float *output,
                         const float *weights, const float *bias,
                         int in_channels, int out_channels,
                         int kernel_size, int input_length) {
    int output_length = input_length - kernel_size + 1;

    for (int oc = 0; oc < out_channels; oc++) {
        for (int o = 0; o < output_length; o++) {
            float sum = bias[oc];
            for (int ic = 0; ic < in_channels; ic++) {
                for (int k = 0; k < kernel_size; k++) {
                    int in_idx = ic * input_length + (o + k);
                    int w_idx = oc * in_channels * kernel_size + ic * kernel_size + k;
                    sum += input[in_idx] * weights[w_idx];
                }
            }
            output[oc * output_length + o] = sum;
        }
    }
}`;
}

// ── ReLU Activation C++ ───────────────────────────────────────────
function generateRelu() {
  return `/**
 * ReLU activation in-place.
 */
static inline void relu(float *data, int n) {
    for (int i = 0; i < n; i++) {
        if (data[i] < 0.0f) data[i] = 0.0f;
    }
}`;
}

// ── Inference Loop C++ ────────────────────────────────────────────
function generateInferenceLoop(arch) {
  return `/**
 * Full autoencoder forward pass.
 * Processes one window of three-phase samples and returns reconstruction error.
 *
 * @param va, vb, vc  Input three-phase voltage windows [WINDOW_SIZE]
 * @param mse_out     Output: mean squared error
 * @param thd_out     Output: total harmonic distortion
 * @return 1 if anomaly detected, 0 otherwise
 */
static int autoencoder_inference(const float *va, const float *vb, const float *vc,
                                  float *mse_out, float *thd_out) {
    /* Clarke Transform */
    float alpha[WINDOW_SIZE], beta[WINDOW_SIZE], zero[WINDOW_SIZE];
    clarke_transform_batch(va, vb, vc, alpha, beta, zero, WINDOW_SIZE);

    /* Compute phase imbalance */
    float imbalance = 0.0f;
    float zero_seq = 0.0f;
    for (int i = 0; i < WINDOW_SIZE; i++) {
        float mag = sqrtf(alpha[i] * alpha[i] + beta[i] * beta[i]);
        imbalance += fabsf(mag - 1.0f);
        zero_seq += fabsf(zero[i]);
    }
    imbalance /= WINDOW_SIZE;
    zero_seq /= WINDOW_SIZE;

    /* THD computation (simplified: fundamental vs harmonics) */
    /* In production, use CMSIS DSP arm_rfft_f32 for optimized FFT */
    float fund_re = 0.0f, fund_im = 0.0f;
    float harmonic_power = 0.0f;
    for (int i = 0; i < WINDOW_SIZE; i++) {
        float angle = 2.0f * PI * i / WINDOW_SIZE;
        fund_re += va[i] * cosf(angle);
        fund_im += va[i] * sinf(angle);
    }
    fund_re /= WINDOW_SIZE;
    fund_im /= WINDOW_SIZE;
    float fund_amp = sqrtf(fund_re * fund_re + fund_im * fund_im);

    if (fund_amp > 1e-6f) {
        for (int h = 2; h <= 50; h++) {
            float h_re = 0.0f, h_im = 0.0f;
            for (int i = 0; i < WINDOW_SIZE; i++) {
                float angle = 2.0f * PI * h * i / WINDOW_SIZE;
                h_re += va[i] * cosf(angle);
                h_im += va[i] * sinf(angle);
            }
            h_re /= WINDOW_SIZE;
            h_im /= WINDOW_SIZE;
            harmonic_power += h_re * h_re + h_im * h_im;
        }
    }

    float thd = (fund_amp > 1e-6f) ? sqrtf(harmonic_power) / fund_amp : 1.0f;
    float mse = 0.4f * imbalance + 0.3f * zero_seq;

    *mse_out = mse;
    *thd_out = thd;

    /* Decision gate: OR rule */
    return (mse > THRESHOLD_MSE || thd > THRESHOLD_THD) ? 1 : 0;
}`;
}

// ── Main Loop C++ ─────────────────────────────────────────────────
function generateMainLoop(platform) {
  const loops = {
    stm32: `/**
 * Main inference loop for STM32.
 * Reads ADC samples, runs inference, and triggers alerts.
 */
int main(void) {
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_ADC1_Init();
    MX_USART2_UART_Init();

    float va_buf[WINDOW_SIZE], vb_buf[WINDOW_SIZE], vc_buf[WINDOW_SIZE];
    float mse, thd;
    int alert_count = 0;

    /* Enable ADC DMA for continuous sampling */
    HAL_ADC_Start_DMA(&hadc1, (uint32_t*)adc_buffer, ADC_BUFFER_SIZE);

    while (1) {
        /* Wait for new window of samples */
        if (!window_ready) continue;

        /* Convert ADC counts to p.u. voltage (assuming 12-bit ADC, 3.3V ref) */
        for (int i = 0; i < WINDOW_SIZE; i++) {
            va_buf[i] = (float)adc_buffer[i * 3]     / 4096.0f * 2.0f - 1.0f;
            vb_buf[i] = (float)adc_buffer[i * 3 + 1] / 4096.0f * 2.0f - 1.0f;
            vc_buf[i] = (float)adc_buffer[i * 3 + 2] / 4096.0f * 2.0f - 1.0f;
        }

        /* Run inference */
        int anomaly = autoencoder_inference(va_buf, vb_buf, vc_buf, &mse, &thd);

        if (anomaly) {
            HAL_GPIO_WritePin(ALERT_PORT, ALERT_PIN, GPIO_PIN_SET);
            alert_count++;

            /* Send alert over UART */
            char msg[128];
            snprintf(msg, sizeof(msg),
                "ALERT: MSE=%.6f THD=%.4f%% Count=%d\\r\\n",
                mse, thd * 100.0f, alert_count);
            HAL_UART_Transmit(&huart2, (uint8_t*)msg, strlen(msg), 100);
        } else {
            HAL_GPIO_WritePin(ALERT_PORT, ALERT_PIN, GPIO_PIN_RESET);
        }

        window_ready = 0;
    }
}`,

    arduino: `/*
 * Main inference loop for Arduino.
 * Reads analog inputs, runs inference, and triggers alerts.
 */

float va_buf[WINDOW_SIZE], vb_buf[WINDOW_SIZE], vc_buf[WINDOW_SIZE];
float mse, thd;
int alert_count = 0;
unsigned long last_sample_time = 0;
const unsigned long sample_interval_us = 100;  // 10 kHz = 100 us
int sample_index = 0;

void setup() {
    Serial.begin(SERIAL_BAUD);
    pinMode(ALERT_LED, OUTPUT);
    analogReference(DEFAULT);  // 5V on Uno, 3.3V on some boards
}

void loop() {
    unsigned long now = micros();
    if (now - last_sample_time < sample_interval_us) return;
    last_sample_time = now;

    /* Read ADC (10-bit on Uno, map to p.u.) */
    float va = (float)analogRead(ADC_PIN_A) / 1024.0f * 2.0f - 1.0f;
    float vb = (float)analogRead(ADC_PIN_B) / 1024.0f * 2.0f - 1.0f;
    float vc = (float)analogRead(ADC_PIN_C) / 1024.0f * 2.0f - 1.0f;

    va_buf[sample_index] = va;
    vb_buf[sample_index] = vb;
    vc_buf[sample_index] = vc;
    sample_index++;

    if (sample_index >= WINDOW_SIZE) {
        /* Run inference */
        int anomaly = autoencoder_inference(va_buf, vb_buf, vc_buf, &mse, &thd);

        if (anomaly) {
            digitalWrite(ALERT_LED, HIGH);
            alert_count++;
            Serial.print("ALERT: MSE=");
            Serial.print(mse, 6);
            Serial.print(" THD=");
            Serial.print(thd * 100.0, 2);
            Serial.print("% Count=");
            Serial.println(alert_count);
        } else {
            digitalWrite(ALERT_LED, LOW);
        }

        sample_index = 0;
    }
}`,

    esp32: `/*
 * Main inference loop for ESP32.
 * Reads ADC, runs inference, and publishes alerts via MQTT.
 */

/* WiFi and MQTT configuration */
const char* ssid = "YOUR_WIFI_SSID";
const char* password = "YOUR_WIFI_PASSWORD";
const char* mqtt_server = "broker.example.com";

WiFiClient espClient;
PubSubClient client(espClient);

float va_buf[WINDOW_SIZE], vb_buf[WINDOW_SIZE], vc_buf[WINDOW_SIZE];
float mse, thd;
int alert_count = 0;
unsigned long last_sample_time = 0;
const unsigned long sample_interval_us = 100;  // 10 kHz
int sample_index = 0;

void reconnect() {
    while (!client.connected()) {
        String clientId = "GridSentinel-";
        clientId += String(random(0xffff), HEX);
        if (client.connect(clientId.c_str())) {
            client.subscribe("grid/alerts");
        } else {
            delay(5000);
        }
    }
}

void setup() {
    Serial.begin(SERIAL_BAUD);
    pinMode(ALERT_LED, OUTPUT);
    WiFi.begin(ssid, password);
    while (WiFi.status() != WL_CONNECTED) delay(500);
    client.setServer(mqtt_server, 1883);
}

void loop() {
    if (!client.connected()) reconnect();
    client.loop();

    unsigned long now = micros();
    if (now - last_sample_time < sample_interval_us) return;
    last_sample_time = now;

    /* Read ADC (12-bit on ESP32, map to p.u.) */
    float va = (float)analogRead(ADC_PIN_A) / 4096.0f * 2.0f - 1.0f;
    float vb = (float)analogRead(ADC_PIN_B) / 4096.0f * 2.0f - 1.0f;
    float vc = (float)analogRead(ADC_PIN_C) / 4096.0f * 2.0f - 1.0f;

    va_buf[sample_index] = va;
    vb_buf[sample_index] = vb;
    vc_buf[sample_index] = vc;
    sample_index++;

    if (sample_index >= WINDOW_SIZE) {
        int anomaly = autoencoder_inference(va_buf, vb_buf, vc_buf, &mse, &thd);

        if (anomaly) {
            digitalWrite(ALERT_LED, HIGH);
            alert_count++;

            /* Publish via MQTT */
            char payload[256];
            snprintf(payload, sizeof(payload),
                "{\\"mse\\":%.6f,\\"thd\\":%.4f,\\"count\\":%d,\\"device\\":\\"esp32\\"}",
                mse, thd * 100.0f, alert_count);
            client.publish("grid/alerts", payload);

            /* Serial output */
            Serial.printf("ALERT: MSE=%.6f THD=%.2f%% Count=%d\\n",
                mse, thd * 100.0f, alert_count);
        } else {
            digitalWrite(ALERT_LED, LOW);
        }

        sample_index = 0;
    }
}`,
  };

  return loops[platform] || loops.stm32;
}

// ── Platform Info ─────────────────────────────────────────────────
export function getPlatformInfo(platform) {
  const info = {
    stm32: {
      name: "STM32F4/H7",
      architecture: "ARM Cortex-M4/M7",
      flash: "512KB–2MB",
      ram: "128KB–1MB",
      features: ["CMSIS DSP", "DMA", "Hardware FPU", "UART/SPI"],
      clock: "168–480 MHz",
    },
    arduino: {
      name: "Arduino Uno/Mega",
      architecture: "AVR ATmega328P/2560",
      flash: "32KB–256KB",
      ram: "2KB–8KB",
      features: ["Analog inputs", "Serial", "Digital I/O"],
      clock: "16 MHz",
    },
    esp32: {
      name: "ESP32/ESP32-S3",
      architecture: "Xtensa LX6/LX7 or RISC-V",
      flash: "4MB–16MB",
      ram: "520KB SRAM",
      features: ["WiFi", "Bluetooth", "MQTT", "Dual-core"],
      clock: "240 MHz",
    },
  };

  return info[platform] || info.stm32;
}

// ── Download Helper ───────────────────────────────────────────────
export function downloadCppFile(code, filename) {
  const blob = new Blob([code], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
